const Traits = {
  Birthday: ["Age"],
  Gender: [
    "Male",
    "Female",
    "Transgender Male",
    "Transgender Female",
    "Gender Variant/Non-Coforming"
  ],
  Race: [
    "American Indian or Alaska Native",
    "Asian",
    "Black or African American",
    "Hispanic or Latino",
    "Native Hawaiian or Other Pacific Islander",
    "White"
  ],
  "Sexual Orientation": [
    "Straight/Heterosexual",
    "Bisexual/Pansexual",
    "Gay/Homosexual",
    "Other"
  ],
  "Political Party": ["Republican", "Democrat", "Libertarian", "Independent"],
  Education: [
    "Did Not Complete High School",
    "Completed High School/GED",
    "Some College",
    "Bachelors",
    "Masters",
    "Doctorate"
  ],
  Salary: ["Salary"],
  Religion: [
    "Christianity",
    "Islam",
    "Judaism",
    "Hinduism",
    "Buddhism",
    "Atheist/Agnostic",
    "Other"
  ],
  "Relationship Status": ["Single", "Married", "In Relationship"],
  Community: ["Rural", "Suburban", "Urban"],
  State: [
    "AL",
    "AK",
    "AZ",
    "AR",
    "CA",
    "CO",
    "CT",
    "DE",
    "FL",
    "GA",
    "HI",
    "ID",
    "IL",
    "IN",
    "IA",
    "KS",
    "KY",
    "LA",
    "ME",
    "MD",
    "MA",
    "MI",
    "MN",
    "MS",
    "MO",
    "MT",
    "NE",
    "NV",
    "NH",
    "NJ",
    "NM",
    "NY",
    "NC",
    "ND",
    "OH",
    "OK",
    "OR",
    "PA",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VT",
    "VA",
    "WA",
    "WV",
    "WI",
    "WY"
  ],
  Height: ["Height"],
  Weight: ["Weight"],
  "Hair Color": ["Brown/Black", "Blonde", "Red", "Other Hair Color"],
  "Eye Color": ["Brown", "Blue", "Green", "Other Eye Color"]
};

export default Traits;
